version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  node:
    container_name: node-tdd-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: './Dockerfile'
    volumes:
      - .:/home/node-tdd-app
    ports:
      - 3333:3333
    depends_on: [mongodb]
